### ISSUE TITLE
Feature: User can delete a restaurant from their favorites list

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/choice.ly#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can unfavorite a restaurant from their favorites list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the heart to unfavorite a restaurant and doing so will remove the restaurant from their favorites list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/80491609/135320356-ba6748d7-4313-44b9-9c5c-47c633f2e701.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a DELETE request to delete a favorited restaurant 
- [x] Create a sql variable to delete from my Favorites table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update details.jsx component to show a non-filled out heart once the heart icon is pressed
- [x] when heart icon is toggled off, do a fetch request to delete and set the state back to false

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
