### ISSUE TITLE
Feature: User can view the details of a restaurant

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/choice.ly#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of a restaurant

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user can click on one of the restaurant selections that they're interested in and they can see the details of that restaurant

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/80491609/133325521-be08bb7b-c6d2-495f-b91e-ae85f318064f.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a GET request to get a specific restaurant
- [x] Update `server/index.js` to handle a GET request to get the recent reviews of a restaurant
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a details component to view the details of a restaurant
- [x] Change the hash routing so that the page changes upon a selection of restaurant
- [x] Import the details component into app.jsx
- [x] Apply the selected class to the restaurant that the user selects so that the user knows what they selected
- [x] Use Promise.all for the two separate fetch requests to get a single restaurant and it's reviews
- [x] User .map to map through the review array and spit out each review bubble
- [x] Clean everything so that it looks pretty through CSS

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
